services:
  - type: web
    name: networksecurity
    env: python
    plan: free # Explicitly set the plan
    pythonVersion: "3.14"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120"